{{- if .Values.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "azure-web-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "azure-web-app.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: {{ .Values.externalSecret.secretStoreKind | default "ClusterSecretStore" }}
  target:
    name: {{ .Values.externalSecret.target.name | default (include "azure-web-app.fullname" .) }}
    creationPolicy: Owner
  data:
    {{- toYaml .Values.externalSecret.data | nindent 4 }}
{{- end }}
